=== Ondrej-vojtisek/bbmri/src/main/webapp/schemas/exportNIS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://bbmri.cz/schemas/biobank/data" xmlns:data="http://bbmri.cz/schemas/biobank/data">
  <xs:element name="patient">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="data:LTS"/>
        <xs:element ref="data:STS"/>
      </xs:sequence>
      <xs:attribute name="rc" use="required">
        <xs:annotation>
          <xs:documentation>identifier of a patient (rodne cislo s rozlisovacim znakem u duplicity)</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="\d+"/>
            <xs:length value="11"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="consent" use="required" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>informed consent (informovany souhlas)</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attributeGroup ref="data:biobankId"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="LTS">
    <xs:annotation>
      <xs:documentation>samples in long-term storage part of the biobank</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="data:tissue"/>
        <xs:element ref="data:blood"/>
        <xs:element ref="data:genome"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="STS">
    <xs:annotation>
      <xs:documentation>samples in short-term storage part of the biobank</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="data:bloodRsv"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tissue">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="data:sampleNos"/>
        <xs:element ref="data:tissueType"/>
        <xs:element ref="data:TNM"/>
        <xs:element ref="data:pTNM"/>
        <xs:element ref="data:grading"/>
        <xs:element ref="data:cutTime"/>
        <xs:element ref="data:freezeTime"/>
      </xs:sequence>
      <xs:attributeGroup ref="data:sampleId"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tissueType">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:maxLength value="2"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="TNM">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:maxLength value="7"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="pTNM">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:maxLength value="7"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="grading">
    <xs:simpleType>
      <xs:restriction base="xs:int">
        <xs:minInclusive value="1"/>
        <xs:maxExclusive value="9"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="cutTime" type="xs:dateTime"/>
  <xs:element name="freezeTime" type="xs:dateTime"/>
  <xs:element name="blood">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="data:sampleNos"/>
        <xs:element ref="data:takingDate"/>
      </xs:sequence>
      <xs:attributeGroup ref="data:sampleId"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="takingDate" type="xs:dateTime"/>
  <xs:element name="genome">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="data:sampleNos"/>
        <xs:element ref="data:tissueType"/>
        <xs:element ref="data:takingDate"/>
      </xs:sequence>
      <xs:attributeGroup ref="data:sampleId"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="bloodRsv">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="data:diagnosis"/>
        <xs:element ref="data:takingDate"/>
      </xs:sequence>
      <xs:attributeGroup ref="data:sampleId"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="diagnosis">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z0-9]+"/>
        <xs:minLength value="3"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:attributeGroup name="biobankId">
    <xs:annotation>
      <xs:documentation>biobank identifier</xs:documentation>
    </xs:annotation>
    <xs:attribute name="biobank" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="[a-zA-Z0-9]+"/>
          <xs:maxLength value="32"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:attributeGroup name="sampleId">
    <xs:attribute name="year" use="required" type="xs:gYear"/>
    <xs:attribute name="number" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:maxLength value="6"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:group name="sampleNos">
    <xs:sequence>
      <xs:element ref="data:samplesNo"/>
      <xs:element ref="data:availableSamplesNo"/>
    </xs:sequence>
  </xs:group>
  <xs:element name="samplesNo" type="xs:int"/>
  <xs:element name="availableSamplesNo" type="xs:int"/>
</xs:schema>

=== Ondrej-vojtisek/bbmri/src/main/webapp/schemas/exportExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<patient xsi:noNamespaceSchemaLocation="exportNIS.xsd"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns="http://bbmri.cz/schemas/biobank/data"
   rc="88050113280" biobank="001MOUBRNO" consent="true">
    <!-- Rodne cislo prodlouzeno o znak duplicity,
    idendifikator biobanky alfanumericke znaky o maximalni delce 32,
     consent: platne hodnoty jsou true/false/1/0 -->

<!-- Long-term samples -->
    <LTS>
        <blood year="2013" number="110">
            <samplesNo>3</samplesNo>
            <availableSamplesNo>0</availableSamplesNo>
            <takingDate>2013-03-30T09:00:00</takingDate>
        </blood>

        <genome year="2013" number="112">
            <samplesNo>3</samplesNo>
            <availableSamplesNo>2</availableSamplesNo>
           <!-- tissueType muze nabyvat hodnot 1,2,4, gD, ... -->
            <tissueType>gD</tissueType>
            <takingDate>20013-03-30T09:00:00</takingDate>
        </genome>

        <tissue year="2013" number="112">
            <!--
            Ujasnit si význam pole number. V NISu se pracuje se dvěmi ID vzorku. jedno je bioptická žádanka což je číslo
            umožňující přiřazení záznamu k operaci, operatérovi a i k fyzickému vzorku v biobance a pak identifikátor
            vzorku v NISu
            -->
            <samplesNo>5</samplesNo>
            <availableSamplesNo>2</availableSamplesNo>
            <tissueType>01</tissueType>
            <!-- viz. TNM klasifikace -->
            <TNM>T1aN0M0</TNM>
            <pTNM>T1bN0M0</pTNM>
            <!-- hodnota z intervalu 1(vcetne) - 9
            Místo hodnoty Grading by bylo lepší uvézt morfologii (ta grading obsahuje)
            -->
            <grading>1</grading>
            <cutTime>2013-01-03T09:00:00</cutTime>
            <freezeTime>2013-04-04T12:00:00</freezeTime>

        </tissue>
    </LTS>

<!-- Short-term samples -->
    <STS>
        <bloodRsv year="2013" number="99">
            <diagnosis>N26</diagnosis>
            <takingDate>2013-04-04T12:00:00</takingDate>
        </bloodRsv>
    </STS>

</patient>

=== Ondrej-vojtisek/bbmri/src/main/webapp/schemas/exportFuchs.xml
<?xml version="1.0" encoding="UTF-8"?>
<patient xsi:noNamespaceSchemaLocation="exportNIS.xsd"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns="http://www.bbmri.cz/schemas/biobank/data"
   rc="88050113280" biobank="001MOUBRNO" consent="true">
    <LTS>
        <tissue>
            <sampleID>
                <year>2004</year>
                <number>3</number>
            </sampleID>
            <sampleNos>
                <samplesNo>10</samplesNo>
                <availableSamplesNo>1</availableSamplesNo>
            </sampleNos>
            <tissueType>2</tissueType>
            <pTNM>0 0 0</pTNM>
            <grading>3</grading>
            <cutTime>2006-10-27T00:00</cutTime>
            <freezeTime>2006-10-27T00:00</freezeTime>
        </tissue>
        <tissue>
            <sampleID>
                <year>2007</year>
                <number>1</number>
            </sampleID>
            <sampleNos>
                <samplesNo>4</samplesNo>
                <availableSamplesNo>1</availableSamplesNo>
            </sampleNos>
            <tissueType>4</tissueType>
            <pTNM>2 1 1</pTNM>
            <grading>9</grading>
            <cutTime>2003-06-24T09:02</cutTime>
            <freezeTime>2003-06-24T10:00</freezeTime>
        </tissue>
        <tissue>
            <sampleID>
                <year>2013</year>
                <number>1</number>
            </sampleID>
            <sampleNos>
                <samplesNo>2</samplesNo>
                <availableSamplesNo>1</availableSamplesNo>
            </sampleNos>
            <tissueType>3</tissueType>
            <pTNM>2 1 1</pTNM>
            <grading>9</grading>
            <cutTime>2013-06-20T06:00</cutTime>
            <freezeTime>2013-06-20T07:00</freezeTime>
        </tissue>
        <tissue>
            <sampleID>
                <year>2013</year>
                <number>1</number>
            </sampleID>
            <sampleNos>
                <samplesNo>1</samplesNo>
                <availableSamplesNo>0</availableSamplesNo>
            </sampleNos>
            <tissueType>4</tissueType>
            <pTNM>2 1 1</pTNM>
            <grading>9</grading>
            <cutTime>2013-06-20T06:00</cutTime>
            <freezeTime>2013-06-20T07:00</freezeTime>
        </tissue>
        <blood>
            <sampleID>
                <year>2006</year>
                <number>2</number>
            </sampleID>
            <sampleNos>
                <samplesNo>4</samplesNo>
                <availableSamplesNo>1</availableSamplesNo>
            </sampleNos>
            <takingDate>2006-10-27</takingDate>
        </blood>
    </LTS>
</patient>
